version: "3.9"
services:
  db:
    image: postgres:16
    container_name: blog-db
    restart: always # Always restart when stoped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234!
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
